# Generated by Django 5.0.6 on 2024-05-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('accno', models.TextField()),
                ('state', models.TextField()),
                ('pin', models.TextField()),
                ('dpd', models.TextField()),
            ],
        ),
    ]
